-- ============================================================
--  Employee Attendance System - Supabase Tables
--  Run this in Supabase SQL Editor (in order)
-- ============================================================

-- 1. Departments
CREATE TABLE departments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) UNIQUE NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Employees
CREATE TABLE employees (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     VARCHAR(20) UNIQUE NOT NULL,
    email           VARCHAR(120) UNIQUE NOT NULL,
    password_hash   VARCHAR(256) NOT NULL,
    first_name      VARCHAR(50) NOT NULL,
    last_name       VARCHAR(50) NOT NULL,
    phone           VARCHAR(20),
    position        VARCHAR(100),
    department_id   BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    role            VARCHAR(20) DEFAULT 'employee',      -- admin, hr, employee
    is_active       BOOLEAN DEFAULT TRUE,
    date_joined     DATE DEFAULT CURRENT_DATE,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Attendance
CREATE TABLE attendance (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    date            DATE NOT NULL DEFAULT CURRENT_DATE,
    clock_in        TIMESTAMPTZ,
    clock_out       TIMESTAMPTZ,
    status          VARCHAR(20) DEFAULT 'present',       -- present, late, absent, half-day
    work_hours      DOUBLE PRECISION,
    notes           VARCHAR(255),
    created_at      TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT unique_attendance_per_day UNIQUE (employee_id, date)
);

-- 4. Leave Requests
CREATE TABLE leave_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    leave_type      VARCHAR(30) NOT NULL,                -- annual, medical, emergency, unpaid
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL,
    reason          TEXT NOT NULL,
    status          VARCHAR(20) DEFAULT 'pending',       -- pending, approved, rejected
    reviewed_by     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    reviewed_at     TIMESTAMPTZ,
    review_notes    VARCHAR(255),
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
--  Indexes (speed up common queries)
-- ============================================================

CREATE INDEX idx_attendance_employee    ON attendance(employee_id);
CREATE INDEX idx_attendance_date        ON attendance(date);
CREATE INDEX idx_leave_employee         ON leave_requests(employee_id);
CREATE INDEX idx_leave_status           ON leave_requests(status);
CREATE INDEX idx_employee_department    ON employees(department_id);
CREATE INDEX idx_employee_active        ON employees(is_active);
